// Code generated by "stringer -type DeclarationKind"; DO NOT EDIT

package gc

import "fmt"

const _DeclarationKind_name = "ConstDeclarationFuncDeclarationImportDeclarationMethodDeclarationTypeDeclarationVarDeclaration"

var _DeclarationKind_index = [...]uint8{0, 16, 31, 48, 65, 80, 94}

func (i DeclarationKind) String() string {
	if i < 0 || i >= DeclarationKind(len(_DeclarationKind_index)-1) {
		return fmt.Sprintf("DeclarationKind(%d)", i)
	}
	return _DeclarationKind_name[_DeclarationKind_index[i]:_DeclarationKind_index[i+1]]
}
